---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 12/22/2020 7:15 PM
---

-- Globals within the mod
MOD_NAME = 'erm_zerg'
FORCE_NAME = 'enemy_erm_zerg'
MOD_VERSION = 000100

DEBUG_MODE = false


-- Attack Types for on_script_trigger_effect
OVERLORD_ATTACK = 'overlord_attack'
DRONE_ATTACK = 'drone_attack'




