---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 12/22/2020 7:15 PM
---

-- Globals within the mod
-- Must be same as the name in info.json and it must be start with erm_ prefix.
MOD_NAME = 'erm_zerg'
-- Must be prefix with "enemy_"
FORCE_NAME = 'enemy_erm_zerg'

DEBUG_MODE = true


-- Attack Types for on_script_trigger_effect
OVERLORD_ATTACK = 'emzrg-old'
DRONE_ATTACK = 'emzrg-drn'
INFESTED_ATTACK = 'emzrg-inf'
BOSS_SPAWN_ATTACK = 'emzrg-bs1'

ZERG_MAP_COLOR = {r=248, g=140, b=20}
TRIGGER_BOSS_DIES = 'embss-die'




