---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 12/22/2020 7:15 PM
---

-- Globals within the mod
-- Must be same as the name in info.json and it must be start with erm_ prefix.
MOD_NAME = 'erm_zerg'
-- Must be prefix with "enemy_"
FORCE_NAME = 'enemy_erm_zerg'

DEBUG_MODE = false


-- Attack Types for on_script_trigger_effect
OVERLORD_SPAWN = 'emzrg-ovl'
QUEEN_SPAWN = 'emzrg-qun'
DRONE_SPAWN = 'emzrg-drn'
SCOURGE_SPAWN = 'emzrg-scg'
SELF_DESTRUCT_ATTACK = 'emzrg-slf'
BOSS_SPAWN_ATTACK = 'emzrg-bs1'
UNITS_SPAWN_ATTACK = 'emzrg-bs2'

ZERG_MAP_COLOR = {r=248, g=140, b=20}
TRIGGER_BOSS_DIES = 'embss-die'




