---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 12/6/2024 9:30 AM
---

if game.surfaces['char'] then
    game.planets['char'].reset_map_gen_settings()
    local map_gen_settings = game.surfaces['char'].map_gen_settings
    local planet_map_gen_settings = game.planets['char'].prototype.map_gen_settings
    map_gen_settings.autoplace_controls = planet_map_gen_settings.autoplace_controls
    map_gen_settings.autoplace_settings = planet_map_gen_settings.autoplace_settings
    map_gen_settings.property_expression_names = planet_map_gen_settings.property_expression_names
    game.surfaces['char'].map_gen_settings = map_gen_settings
end 