---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/26/2022 11:52 PM
---
require("__erm_zerg__/global")

local ERMConfig = require("__enemyracemanager__/lib/global_config")
local ERMDataHelper = require("__enemyracemanager__/lib/rig/data_helper")
local AnimationDB = require("__erm_zerg_hd_assets__/animation_db")

local FALLING_PROJECTILE = 'falling_projectile'
local damage_multiplier = settings.startup["enemyracemanager-damage-multipliers"].value
--- Basic Attack #1
local create_blood_cloud_projectile = function(type)
    type = type or "projectile"
    local data = {
        type = "projectile",
        name = MOD_NAME.."--blood-cloud--"..type,
        flags = { "not-on-map" },
        acceleration = 0.01,
        max_speed = 0.8,
        collision_box = {{-0.5,-0.5},{0.5, 0.5}},
        direction_only = true,
        force_condition = "enemy",
        hit_collision_mask = { layers = {player = true, train = true, car=true, object = true, [ERMDataHelper.getFlyingLayerName()] =  true} },
        final_action = {
            type = "direct",
            action_delivery = {
                type = "instant",
                target_effects = {
                    {
                        type = "create-entity",
                        entity_name = MOD_NAME.."--blood-cloud-explosion",
                        trigger_created_entity = false
                    },
                    {
                        type = "create-smoke",
                        show_in_tooltip = true,
                        entity_name = MOD_NAME .. "--blood-cloud"
                    },
                }
            }
        },
        animation = AnimationDB.get_single_animation("projectiles","guardian","projectile")
    }

    return data
end

--- Basic Attack #2
local create_acid_cloud_projectile = function(type)
    type = type or "projectile"
    local data = {
        type = "projectile",
        name = MOD_NAME.."--acid-cloud--"..type,
        flags = { "not-on-map" },
        acceleration = 0.02,
        max_speed = 1,
        collision_box = {{-0.5,-0.5},{0.5, 0.5}},
        direction_only = true,
        force_condition = "enemy",
        hit_collision_mask = { layers = {player = true, train = true,car=true, object = true, [ERMDataHelper.getFlyingLayerName()] =  true} },
        final_action = {
            type = "direct",
            action_delivery = {
                type = "instant",
                target_effects = {
                    {
                        type = "create-entity",
                        entity_name = MOD_NAME.."--acid-cloud-explosion",
                        trigger_created_entity = false
                    },
                    {
                        type = "create-smoke",
                        show_in_tooltip = true,
                        entity_name = MOD_NAME .. "--acid-cloud"
                    },
                }
            }
        },
        animation = AnimationDB.get_single_animation("projectiles","guardian","projectile")
    }
    
    return data
end

local create_damage_cloud = function (name, target_effects, radius, duration, cooldown)
    radius = radius or 2
    duration = duration or 120
    cooldown = cooldown or 15
    return  {
        name = MOD_NAME.."--"..name,
        type = "smoke-with-trigger",
        flags = { "not-on-map" },
        show_when_smoke_off = true,
        particle_count = 1,
        render_layer = "explosion",
        affected_by_wind = false,
        duration = duration,
        cyclic = true,

        animation = util.empty_sprite(),
        action = {
            type = "direct",
            ignore_collision_condition = true,
            force = "not-same",
            action_delivery = {
                type = "instant",
                target_effects = {
                    type = "nested-result",
                    action = {
                        type = "area",
                        force = "not-same",
                        radius = radius,
                        ignore_collision_condition = true,
                        action_delivery = {
                            type = "instant",
                            target_effects = target_effects
                        }
                    }
                }
            }
        },
        action_cooldown = cooldown
    }
end

local create_healing_cloud = function (name, target_effects, radius, duration, cooldown)
    radius = radius or 2
    duration = duration or 120
    cooldown = cooldown or 15
    return  {
        name = MOD_NAME.."--"..name,
        type = "smoke-with-trigger",
        flags = { "not-on-map" },
        show_when_smoke_off = true,
        particle_count = 1,
        render_layer = "explosion",
        affected_by_wind = false,
        duration = duration,
        cyclic = true,

        animation = util.empty_sprite(),
        action = {
            type = "direct",
            ignore_collision_condition = true,
            force = "same",
            action_delivery = {
                type = "instant",
                target_effects = {
                    type = "nested-result",
                    action = {
                        type = "area",
                        force = "same",
                        radius = radius,
                        ignore_collision_condition = true,
                        action_delivery = {
                            type = "instant",
                            target_effects = target_effects
                        }
                    }
                }
            }
        },
        action_cooldown = cooldown
    }
end


local create_blood_mist_projectile = function(type, radius, damage)
    type = type or "projectile"
    radius  = radius or 8
    damage  = damage or 1000
    local data = {
        type = "projectile",
        name = MOD_NAME.."--blood-mist--"..type,
        flags = { "not-on-map" },
        acceleration = 0.0025,
        max_speed = 0.6,
        collision_box = {{-0.5,-0.5},{0.5, 0.5}},
        direction_only = true,
        force_condition = "enemy",
        hit_collision_mask = { layers = {player = true, train = true, car=true, object = true, [ERMDataHelper.getFlyingLayerName()] =  true} },
        final_action = {
            type = "direct",
            action_delivery = {
                type = "instant",
                target_effects = {
                    {
                        type = "create-entity",
                        entity_name = MOD_NAME.."--dark-swarm-80-blood-explosion",
                        trigger_created_entity = false
                    },
                    {
                        type = "create-smoke",
                        show_in_tooltip = true,
                        entity_name = MOD_NAME .. "--blood-mist"
                    },
                }
            }
        },
        animation = AnimationDB.get_single_animation("projectiles","guardian","projectile")
    }
    
    if type == FALLING_PROJECTILE then
        data.collision_box = nil
    end

    return data
end

local create_swamp_cloud_projectile = function(script_attack, type)
    type = type or "projectile"
    local data =  {
        type = "projectile",
        name = MOD_NAME.."--swamp-cloud-"..script_attack.."--"..type,
        flags = { "not-on-map" },
        acceleration = 0.0025,
        max_speed = 0.5,
        collision_box = {{-1,-1},{1, 1}},
        direction_only = true,
        force_condition = "enemy",
        hit_collision_mask = { layers = {player = true, train = true, car=true, object = true, [ERMDataHelper.getFlyingLayerName()] =  true} },
        final_action = {
            type = "direct",
            action_delivery = {
                type = "instant",
                target_effects = {
                    {
                        type = "create-entity",
                        entity_name = MOD_NAME.."--dark-swarm-explosion",
                    },
                    {
                        type = "create-smoke",
                        show_in_tooltip = true,
                        entity_name = MOD_NAME .. "--swamp-cloud"
                    },
                    {
                        type = "script",
                        effect_id = script_attack,
                    }
                }
            }
        },
        animation = AnimationDB.get_single_animation("projectiles","dark_swam","explosion")
    }

    if type == FALLING_PROJECTILE then
        data.collision_box = nil
    end
    
    return data
end

--- Cluster Grenade based on blood cloud projectile
local create_blood_cluster_grenade = function(type)
    type = type or "projectile"
    local data =  {
        type = "projectile",
        name = MOD_NAME.."--blood-cluster-grenade--"..type,
        flags = { "not-on-map" },
        acceleration = 0,
        --collision_box = {{-0.5,-0.5},{0.5, 0.5}},
        direction_only = true,
        force_condition = "enemy",
        action = {
            {
                type = "direct",
                action_delivery = {
                    type = "instant",
                    target_effects = {
                        {
                            type = "create-entity",
                            entity_name = MOD_NAME.."--blood-cloud-explosion",
                        },
                        {
                            type = "create-smoke",
                            show_in_tooltip = true,
                            entity_name = MOD_NAME .. "--blood-cloud"
                        }
                    }
                }
            },
            {
                type = "cluster",
                cluster_count = 4,
                distance = 16,
                distance_deviation = 5,
                action_delivery = {
                    type = "projectile",
                    projectile = MOD_NAME.."--blood-cloud--projectile",
                    direction_deviation = 0.6,
                    max_range = 32,
                    starting_speed = 0.25,
                    starting_speed_deviation = 0.3
                }
            }
        },
        animation = AnimationDB.get_single_animation("projectiles","guardian","projectile"),
    }
    
    return data
end

--- Cluster Grenade based on blood cloud projectile
local create_acid_cluster_grenade = function(type)
    type = type or "projectile"
    local data = {
        type = "projectile",
        name = MOD_NAME.."--acid-cluster-grenade--"..type,
        flags = { "not-on-map" },
        acceleration = 0,
        --collision_box = {{-0.5,-0.5},{0.5, 0.5}},
        direction_only = true,
        force_condition = "enemy",
        action = {
            {
                type = "direct",
                action_delivery = {
                    type = "instant",
                    target_effects = {
                        {
                            type = "create-entity",
                            entity_name = MOD_NAME.."--acid-cloud-explosion",
                        },
                        {
                            type = "create-smoke",
                            show_in_tooltip = true,
                            entity_name = MOD_NAME .. "--acid-cloud"
                        }
                    }
                }
            },
            {
                type = "cluster",
                cluster_count = 6,
                distance = 8,
                distance_deviation = 5,
                action_delivery = {
                    type = "projectile",
                    projectile = MOD_NAME.."--acid-cloud--projectile",
                    direction_deviation = 0.6,
                    starting_speed = 0.25,
                    starting_speed_deviation = 0.05,
                    max_range = 32
                }
            }
        },
        animation = AnimationDB.get_single_animation("projectiles","guardian","projectile"),
    }


    if type == FALLING_PROJECTILE then
        data.collision_box = nil
    end
    
    return data
end

data:extend({
    create_blood_cloud_projectile(),
    create_damage_cloud("blood-cloud", {
        type = "damage",
        --- process 4 ticks per second
        damage = { amount = 150 * damage_multiplier, type = "acid" },
        apply_damage_to_trees = true
    },  5,120),
    create_acid_cloud_projectile(),
    create_damage_cloud("acid-cloud", {{
                                             type = "damage",
                                             --- process 4 ticks per second
                                             damage = { amount = 100 * damage_multiplier, type = "acid" },
                                             apply_damage_to_trees = false
                                         },{
                                             type = "create-sticker",
                                             sticker = "5-075-slowdown-sticker",
                                             show_in_tooltip = true,
                                         }}, 5,120),
    create_blood_mist_projectile(),
    create_damage_cloud("blood-mist", {{
                                           type = "damage",
                                           --- process 4 ticks per second
                                           damage = { amount = 125 * damage_multiplier, type = "acid" },
                                           apply_damage_to_trees = false
                                           },{
                                               type = "damage",
                                               --- process 4 ticks per second
                                               damage = { amount = 75 * damage_multiplier, type = "poison" },
                                               apply_damage_to_trees = false
                                        }}, 8,120),
    create_swamp_cloud_projectile(BOSS_SPAWN_ATTACK),
    create_swamp_cloud_projectile(UNITS_SPAWN_ATTACK),
    create_swamp_cloud_projectile(UNITS_SPAWN_ATTACK_2X),
    create_blood_cluster_grenade(FALLING_PROJECTILE),
    create_acid_cluster_grenade(FALLING_PROJECTILE),
    create_swamp_cloud_projectile(BOSS_SPAWN_ATTACK,FALLING_PROJECTILE),
    create_healing_cloud("swamp-cloud", {{
        type = "damage",
        --- process 4 ticks per second
        damage = { amount = 500 * -1, type = "healing" },
        apply_damage_to_trees = true
    }},  10,180),
    create_blood_cluster_grenade(),  -- Add the new cluster grenade
})

-- Basic attack fissure
local basic_attack_fissure_prototype = make_demolisher_fissure_attack(MOD_NAME..'--basic', MOD_NAME..'-basic', 2,  2.5 * damage_multiplier)
-- Rename fissure explosion to be compatible with boss attack
basic_attack_fissure_prototype[1].name = basic_attack_fissure_prototype[1].name..'--direct'
for _, prototype in pairs(basic_attack_fissure_prototype) do
    data:extend({
        prototype
    })
end 