---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 12/21/2020 4:42 PM
---



local ERM_UnitHelper = require("__enemyracemanager__/lib/rig/unit_helper")
local GlobalConfig = require("__enemyracemanager__/lib/global_config")
local ERM_DebugHelper = require("__enemyracemanager__/lib/debug_helper")
local ERM_Config = require("__enemyracemanager__/lib/global_config")
local ZergSound = require("__erm_zerg_hd_assets__/sound")

-- This is a custom autoplace that accept custom forces. search "autoplace ="
local CreepFunction = require("__erm_zerg__/prototypes/creep_function")
local AnimationDB = require("__erm_zerg_hd_assets__/animation_db")
local enemy_autoplace = require ("__enemyracemanager__/prototypes/enemy-autoplace")
local name = "overmind"

-- Hitpoints


local pollution_absorption_absolute = 300
-- Spawning cooldown is based on evolution factor
local spawning_radius = 64

local max_friends_around_to_spawn = 200
--- Spawn Table
--- This control how unit spawns based on evolution factor.  It divided into 6 sections by 0.2.
--- ERM have 3 tiers, Tier 1 - 0.0 - 0.4, Tier 2 - 0.4 - 0.8, Tier 3 - 0.8 - 1.0
--- You can adjust the spawn rate at 0.2 interval as you please.
local spawn_table = function()
    local res = {}
    --Tire 1
    res[1] = { MOD_NAME .. "--zergling--6", { { 0.0, 0.7 }, { 0.2, 0.7 }, { 0.4, 0.6 }, { 0.6, 0.3 }, { 0.8, 0.15 }, {1.0, 0.1} } }
    res[2] = { MOD_NAME .. "--hydralisk--6", { { 0.0, 0.3 }, { 0.2, 0.3 }, { 0.4, 0.3 }, { 0.6, 0.2 }, { 0.8, 0.15 }, {1.0, 0.1} } }
    res[3] = { MOD_NAME .. "--mutalisk--6", { { 0.0, 0.0 }, { 0.2, 0.0 }, { 0.4, 0.1 }, { 0.6, 0.1 }, { 0.8, 0.15 }, {1.0, 0.1} } }
    --Tire 2
    res[4] = { MOD_NAME .. "--lurker--6", { { 0.0, 0.0 }, { 0.2, 0.0 }, { 0.4, 0.0 }, { 0.6, 0.0 }, { 0.8, 0.0 }, {1.0, 0.1} } }
    res[5] = { MOD_NAME .. "--guardian--6", { { 0.0, 0.0 }, { 0.2, 0.0 }, { 0.4, 0.0 }, { 0.6, 0.0 }, { 0.8, 0.0 }, {1.0, 0.1} } }
    res[6] = { MOD_NAME .. "--devourer--6", { { 0.0, 0.0 }, { 0.2, 0.0 }, { 0.4, 0.0 }, { 0.6, 0.2 }, { 0.8, 0.2 }, {1.0, 0.1} } }
    res[7] = { MOD_NAME .. "--overlord--6", { { 0.0, 0.0 }, { 0.2, 0.0 }, { 0.4, 0.0 }, { 0.6, 0.1 }, { 0.8, 0.2 }, {1.0, 0.1} } }
    --Tier 3
    res[8] = { MOD_NAME .. "--drone--6", { { 0.0, 0.0 }, { 0.2, 0.0 }, { 0.4, 0 }, { 0.6, 0.1 }, { 0.8, 0.1 }, {1.0, 0.1} } }
    res[9] = { MOD_NAME .. "--ultralisk--6", { { 0.0, 0.0 }, { 0.2, 0.0 }, { 0.4, 0 }, { 0.6, 0 }, { 0.8, 0.0 }, {1.0, 0.1} } }
    res[10] = { MOD_NAME .. "--defiler--6", { { 0.0, 0.0 }, { 0.2, 0.0 }, { 0.4, 0 }, { 0.6, 0 }, { 0.8, 0.0 }, {1.0, 0.1} } }
    res[11] = { MOD_NAME .. "--queen--6", { { 0.0, 0.0 }, { 0.2, 0.0 }, { 0.4, 0 }, { 0.6, 0 }, { 0.8, 0.0 }, {1.0, 0.1} } }
    res[12] = { MOD_NAME .. "--infested--6", { { 0.0, 0.0 }, { 0.2, 0.0 }, { 0.4, 0 }, { 0.6, 0 }, { 0.8, 0.0 }, {1.0, 0.05} } }
    return res
end

local collision_box = { { -3.5, -4.25 }, { 3.25, 3 } }
-- Map generator bounding box should always at least 1 unit wider than collision_box. This prevent units from getting stuck.
local map_generator_bounding_box = { { -4.5, -5.25 }, { 4.25, 4 } }
local selection_box = { { -3.5, -4.25 }, { 3.25, 3 } }

function ErmZerg.make_boss_hive(level)
    data:extend({
        {
            type = "unit-spawner",
            name = MOD_NAME .. "--boss-" .. name .. "--" .. level,
            localised_name = { "entity-name." .. MOD_NAME .. "--" .. name, GlobalConfig.QUALITY_MAPPING[level] },
            icon = "__erm_zerg_hd_assets__/graphics/entity/icons/buildings/advisor.png",
            icon_size = 64,
            flags = { "placeable-player", "placeable-enemy", "breaths-air" },
            max_health = GlobalConfig.BOSS_BUILDING_HITPOINT[level],
            order = MOD_NAME .. "--building--" .. name .. "--".. level,
            subgroup = "enemies",
            working_sound = ZergSound.building_working_sound("hive", 0.9),
            dying_sound = ZergSound.building_dying_sound(0.9),
            resistances = {
                { type = "acid", percent = 75 },
                { type = "poison", percent = 75 },
                { type = "physical", percent = 80 },
                { type = "fire", percent = 75 },
                { type = "explosion", percent = 75 },
                { type = "laser", percent = 75 },
                { type = "electric", percent = 75 },
                { type = "cold", percent = 75 }
            },
            healing_per_tick = 0,
            map_color = ERM_UnitHelper.format_map_color(settings.startup["enemy_erm_zerg-map-color"].value),
            collision_box = collision_box,
            map_generator_bounding_box = map_generator_bounding_box,
            selection_box = selection_box,
            absorptions_per_second = { pollution = { absolute = pollution_absorption_absolute, proportional = 0.01 } },
            corpse = "zerg--large-base-corpse",
            dying_explosion = "zerg--building-explosion",
            dying_trigger_effect = {
                {
                    type = "script",
                    effect_id = TRIGGER_BOSS_DIES,
                }
            },
            max_count_of_owned_units = GlobalConfig.BOSS_BUILDING_UNIT[level],
            max_friends_around_to_spawn = max_friends_around_to_spawn,
            graphics_set = {
                animations = AnimationDB.get_layered_animations("buildings", name, "run")
            },
            result_units = spawn_table(ERM_Config.MAX_LEVELS),
            -- With zero evolution the spawn rate is 6 seconds, with max evolution it is 2.5 seconds
            spawning_cooldown = GlobalConfig.BOSS_SPAWN_TIMER[level],
            spawning_radius = spawning_radius,
            spawning_spacing = 3,
            max_spawn_shift = 0,
            max_richness_for_spawn_shift = 100,
            -- distance_factor used to be 1, but Twinsen says:
            -- "The number or spitter spwners should be roughly equal to the number of biter spawners(regardless of difficulty)."
            -- (2018-12-07)
            autoplace = nil,
            call_for_help_radius = 50,
            -- Remove the following if you don"t want creep under your base.
            spawn_decorations_on_expansion = true,
            spawn_decoration =  CreepFunction.getSpawnerCreep(),
        }
    })
end