---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 12/21/2020 7:32 PM
---
require("__base__/prototypes/entity/spawner-animation")

local AnimationDB = require("__erm_zerg_hd_assets__/animation_db")
data:extend({
    {
        type = "corpse",
        name = MOD_NAME.."--small-base-corpse",
        flags = { "placeable-neutral", "not-on-map" },
        icon = "__erm_zerg_hd_assets__/graphics/entity/icons/buildings/advisor.png",
        icon_size = 64,
        collision_box = { { -2, -2 }, { 2, 2 } },
        selection_box = { { -2, -2 }, { 2, 2 } },
        selectable_in_game = false,
        dying_speed = 0.04,
        time_before_removed = minute * settings.startup["enemyracemanager-enemy-corpse-time"].value,
        subgroup = "corpses",
        order = "c[corpse]-c[small-zerg-base-corpse]",
        final_render_layer = "remnants",
        animation = AnimationDB.get_layered_animations("death", "small_rubble", "run")
    },
    {
        type = "corpse",
        name = MOD_NAME.."--large-base-corpse",
        flags = { "placeable-neutral",  "not-on-map" },
        icon = "__erm_zerg_hd_assets__/graphics/entity/icons/buildings/advisor.png",
        icon_size = 64,
        collision_box = { { -2, -2 }, { 2, 2 } },
        selection_box = { { -2, -2 }, { 2, 2 } },
        selectable_in_game = false,
        dying_speed = 0.04,
        time_before_removed = minute * settings.startup["enemyracemanager-enemy-corpse-time"].value,
        subgroup = "corpses",
        order = "c[corpse]-c[large-zerg-base-corpse]",
        final_render_layer = "remnants",
        animation = AnimationDB.get_layered_animations("death", "large_rubble", "run")
    },
    {
        type = "explosion",
        name = MOD_NAME.."--building-explosion",
        icon = "__erm_zerg_hd_assets__/graphics/entity/icons/buildings/advisor.png",
        icon_size = 64,
        subgroup = "explosions",
        flags = { "not-on-map" },
        hidden = true,
        order = "zerg-explosions",
        render_layer = "explosion",
        animations = AnimationDB.get_layered_animations("death", "large_building", "explosion")
    },
    {
        type = "explosion",
        name = MOD_NAME.."--terran-building-xlarge-explosion",
        flags = { "not-on-map" },
        subgroup = "explosions",
        order = "zerg-terran-xlarge-explosion",
        animations = AnimationDB.get_layered_animations("death", "terran_cmd", "explosion")
        --light = {intensity = 1, size = 50, color = {r=1.0, g=1.0, b=1.0}},
    },
    {
        type = "corpse",
        name = MOD_NAME.."--terran-large-base-corpse",
        flags = { "placeable-neutral",  "not-on-map" },
        icon = "__erm_zerg_hd_assets__/graphics/entity/icons/buildings/advisor.png",
        icon_size = 64,
        collision_box = { { -2, -2 }, { 2, 2 } },
        selection_box = { { -2, -2 }, { 2, 2 } },
        selectable_in_game = false,
        dying_speed = 0.04,
        time_before_removed = minute * settings.startup["enemyracemanager-enemy-corpse-time"].value,
        subgroup = "corpses",
        order = "c[corpse]-c[zerg-large-terran-base-corpse]",
        final_render_layer = "remnants",
        animation = AnimationDB.get_layered_animations("death", "small_building", "explosion")
    },
    {
        type = "explosion",
        name = MOD_NAME.."--building-explosion-small",
        icon = "__erm_zerg__/graphics/entity/icons/buildings/advisor.png",
        icon_size = 64,
        subgroup = "explosions",
        flags = { "not-on-map" },
        hidden = true,
        order = "zerg-explosions",
        render_layer = "explosion",
        animations = AnimationDB.get_layered_animations("death", "small_building", "explosion")
    },
});