---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/28/2022 8:19 PM
---
local ErmBossAttackRemote = require('__enemyracemanager__/lib/helper/boss_attack_helper')
local ErmBossAttackProcessor = require('__enemyracemanager__/lib/boss_attack_processor')

ErmBossAttackRemote.basic_attacks =
{
    projectile_name = {'blood-cloud','acid-cloud','blood-fire'},
    projectile_type = {
        ErmBossAttackProcessor.TYPE_PROJECTILE,
        ErmBossAttackProcessor.TYPE_PROJECTILE,
        ErmBossAttackProcessor.TYPE_PROJECTILE
    },
    projectile_chance = {25, 25, 100},
    projectile_count = {1, 1, 1},
    projectile_spread = {1, 1, 2}
}

return ErmBossAttackRemote