---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 12/23/2020 8:27 PM
---

local CustomAttackHelper = require('__enemyracemanager__/lib/helper/custom_attack_helper')
local ERMConfig = require('__enemyracemanager__/lib/global_config')

local CustomAttacks = {}

CustomAttacks.valid = CustomAttackHelper.valid
CustomAttacks.clearTimeToLiveUnits = CustomAttackHelper.clear_time_to_live_units

function CustomAttacks.process_overlord(event)
    local race_settings = CustomAttackHelper.get_race_settings(MOD_NAME)
    CustomAttackHelper.drop_unit(event, MOD_NAME, 'broodling', 3)
    CustomAttackHelper.drop_unit(event, MOD_NAME, 'scourge', 2)
    if CustomAttackHelper.can_spawn(75) then
        CustomAttackHelper.drop_unit(event, MOD_NAME, CustomAttackHelper.get_unit(MOD_NAME, 'droppable_units'))
    end
    if race_settings.tier == 3 and CustomAttackHelper.can_spawn(40) then
        CustomAttackHelper.drop_unit(event, MOD_NAME, 'zergling', 2)
        if CustomAttackHelper.can_spawn(20) then
            CustomAttackHelper.drop_unit(event, MOD_NAME,  CustomAttackHelper.get_unit(MOD_NAME, 'droppable_units'))
        end
    end
end

function CustomAttacks.process_queen(event)
    local race_settings = CustomAttackHelper.get_race_settings(MOD_NAME)
    CustomAttackHelper.drop_unit_at_target(event, MOD_NAME, 'broodling', 2)
    if CustomAttackHelper.can_spawn(33) then
        CustomAttackHelper.drop_unit_at_target(event, MOD_NAME, 'broodling', 1)
    end
    if race_settings.tier == 3 and CustomAttackHelper.can_spawn(10) then
        CustomAttackHelper.drop_unit_at_target(event, MOD_NAME, 'zergling', 2)
    end
end

function CustomAttacks.process_scourge_spawn(event)
    CustomAttackHelper.drop_unit(event, MOD_NAME, 'scourge', 1)
end

function CustomAttacks.process_drone(event)
    CustomAttackHelper.drop_unit(event, MOD_NAME, CustomAttackHelper.get_unit(MOD_NAME, 'construction_buildings'))
    event.source_entity.destroy()
end

function CustomAttacks.process_self_destruct(event)
    event.source_entity.destroy()
end

function CustomAttacks.process_boss_units(event, batch_size)
    batch_size = batch_size or 12
    CustomAttackHelper.drop_boss_units(event, MOD_NAME, ERMConfig.boss_spawn_size * batch_size)
end

function CustomAttacks.process_batch_units(event, batch_size)
    batch_size = batch_size or 8
    CustomAttackHelper.drop_batch_units(event, MOD_NAME, ERMConfig.boss_spawn_size * batch_size)
end

return CustomAttacks