---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 2/8/2023 9:02 PM
---
require("util")
local ErmConfig = require("__enemyracemanager__/lib/global_config")
local CustomAttacks = require("scripts/custom_attacks")

local RemoteAPI = {}

---
--- Register new milestones
---
function RemoteAPI.milestones_preset_addons()
    --local boss_level = ErmConfig.BOSS_LEVELS
    local preset = {
        ["erm_zerg"] = {
            required_mods = {"erm_zerg"},
            milestones = {
                {type="group", name="Kills"},
                {type="kill", name="enemy_erm_zerg--hive--5",  quantity=1},
                {type="kill", name="enemy_erm_zerg--hive--10",  quantity=1},
                {type="kill", name="enemy_erm_zerg--hive--15",  quantity=1},
                {type="kill", name="enemy_erm_zerg--hive--20",  quantity=1, next="x10"},
            }
        },
    }

    --preset["erm_zerg_boss"] = {
    --    required_mods = {"erm_zerg"},
    --    milestones = {
    --        {type="group", name="ERM Boss Kills"},
    --        {type="kill", name="enemy_erm_zerg--overmind--"..boss_level[1],  quantity=1},
    --        {type="kill", name="enemy_erm_zerg--overmind--"..boss_level[2],  quantity=1},
    --        {type="kill", name="enemy_erm_zerg--overmind--"..boss_level[3],  quantity=1},
    --        {type="kill", name="enemy_erm_zerg--overmind--"..boss_level[4],  quantity=1},
    --        {type="kill", name="enemy_erm_zerg--overmind--"..boss_level[5],  quantity=1},
    --    }
    --}

    return preset
end

---
--- Print global for debug purpose when you run remote.call("enemyracemanager_debug", "print_global")"
---
function RemoteAPI.print_global()
    helpers.write_file("erm_zerg/erm-global.json", helpers.table_to_json(util.copy(storage)))
end

---
--- This is REQUIRED to register ERM mods for control stage.
---
function RemoteAPI.register_new_enemy_race()
    return MOD_NAME
end

--- Refresh custom attack race setting cache
function RemoteAPI.refresh_custom_attack_cache()
    CustomAttacks.get_race_settings(MOD_NAME, true)
end


return RemoteAPI
